paper.md
Edits for JOSS review:
https://github.com/openjournals/joss-reviews/issues/1725
- use "repeatability" for measurements repeated at short time intervals to get a dispersion metric, "replicability" for new studies confirming findings
=> in-text citation syntax; terminology fix

pypulseq/Sequence/block.py, pypulseq/Sequence/read_seq.py, pypulseq/Sequence/sequence.py
This code edit is a quick fix to enable JEMRIS-generated pulseq .seq files (of an older version) to be read. The difference between the old and new Pulseq versions is in the number of fields for RF and trapezoidal gradients. 
* For RF pulses, PyPulseq 1.2.0 version uses **[id, amplitude, mag_id, phase_id, delay, freq, phase]**, but the JEMRIS version uses **[id, amplitude, mag_id, phase_id, freq, phase]**
* For trapezoidal gradients, PyPulseq 1.2.0 uses **[id, amplitude, rise, flat, fall, delay]**, but JEMRIS uses **[id, amplitude, rise, flat, fall]**
**NOTE : An empty section, [JEMRIS], must be manually added to the seq file before seq.read() can be called to parse it.**
Example:
```
[JEMRIS]
[DEFINITIONS]
id 1
Num_Blocks 192
[BLOCKS]
1  0  1   0   0   0  0
2  1  0   0   0   0  0
3  0  0 …
```
=> Enable reading of JEMRIS-generated .seq files

pypulseq/compress_shape.py
Change quantization factor in _compress_shape.py_ from 1e-8 to the MATLAB default value 1e-7. This solves issue https://github.com/imr-framework/pypulseq/issues/42.
=> change quant_factor to match MATLAB implementation

setup.py
version.py was not added as an install target and not copied into install directory. This causes an exception when imported from sequence.py. This commit adds it as py_module to setup.py.
=> Fix missing install module for version.py

pypulseq/Sequence/ext_test_report.py
Some arrays were incorrectly sliced, which caused slew rate to be calculated incorrectly.
Also fixes a typo in units.
=> Fix the magnitude slew rate calculation in the report.

pypulseq/Sequence/sequence.py
The way extended trapezoids are added to the waveforms array was incorrect due to the outermost list not being numpy array, (thus, not having `.shape` property), and being wrapped in an additional list, which caused the shape to be (2, 1, N) instead of (2, N), where N is the number of waveform points. Both of these bugs caused separate exceptions.
=> Fix incorrect array creation at waveform_and_gradients().

pypulseq/Sequence/block.py
Missing parenthesis in `get_block()` caused incorrect timescale of arbitrary gradients.
=> Add missing paranthesis in get_block() for arb grad times.

pypulseq/Sequence/sequence.py, pypulseq/points_to_waveform.py
=> Gradient waveforms fix

pypulseq/Sequence/sequence.py
This PR adds an optional input parameter to seq.plot() that controls if plt.show() is to be called by the function or by the user. This is useful for Matplotlib, since, once show() is called, the rest of the script will be blocked till the plots are closed, meaning, no further modification on the plots can be done by the user.
A very convenient use case for me is adding data cursors, similar to Matlab's data tips using the [mplcursors](https://mplcursors.readthedocs.io/en/stable/index.html) library.
=> [Feature Suggestion] Option to call plt.show() later for plotting.

pypulseq/Sequence/sequence.py
This commit fixes the bugs introduced in #84 due to numpy's rounding function.
np.round outputs the value as np.float64, which can not be automatically cast as int, thus, can not be used for slicing the arrays.
=> Fix side effects of using numpy.round

pypulseq/make_arbitrary_rf.py
make_arbitrary_rf.py has a missing shape_dur property.
=> Add missing shape_dur property to arbitrary RF.

pypulseq/Sequence/sequence.py
Waveforms and times with append RF parameter is not functioning properly, due to improper casts and some missing logics. Also, it was omitting the phase and frequency offsets.
This is a hacky fix and open to discussion. Upstream MATLAB implementation uses cell arrays for storing the time/waveform pairs, which is more flexible than the numpy arrays and nested lists used here. As the RF waveform is complex, usage of np array forces the associated time points to be complex as well, which is a bit awkward and inefficient.
I have two proposals for a better solution:
1) We can switch to dictionaries, and only the time points and waveform would be np arrays. Example usage:
```python
waves['gx']['t'] # For time points
waves['gx']['s'] # For waveform
waves['rf']['s'] # For waveform (only this one …
```
=> waveforms_and_times append RF fixes

pypulseq/Sequence/block.py, pypulseq/Sequence/read_seq.py, pypulseq/Sequence/sequence.py, pypulseq/compress_shape.py
With the current requirements in [setup.py](https://github.com/imr-framework/pypulseq/blob/dev/setup.py#L37) numpy >=1.20 will be installed where `np.int` is deprecated.
Changing all occurrences of `np.int` to `np.int32` is compatible with both `1.19.5 <= numpy <= 1.20.0`, and `numpy >= 1.20.0` (tested with 1.23.5). `np.int` can also be changed to `np.int64` if necessary.
=> np.int is deprecated in numpy>=1.20.0

pypulseq/calc_rf_bandwidth.py, pypulseq/make_adiabatic_pulse.py
When trying to use a slice selective adiabatic hypsec pulse, I got several errors related to the calculation of the bandwidth of the hypsec pulse. I fixed the obvious ones like a wrong import of _calc_rf_center()_ in _calc_rf_bandwidth()_ and a wrong attribute name (rf.sig instead of rf.signal) and provide a new solution for the ___find_flank()_ function:
```python
def __find_flank(x, f, c):
m = np.max(np.abs(f))
f = np.abs(f) / m
i = np.argwhere(f > c)[0]
return x[i]
```
Using calc_rf_bandwidth() with a cut_off value of 0.5 instead of 0.1 (which makes sense imo because the signal gets normalized to 1 and we are interested in the width at half maximum ?!) yields a bw of 1280 Hz, which is close to the literaure value of ~ 1250 Hz for the hypsec pulse with default settings (beta = 800, mu …
=> fix calculation of bandwidth of adiabatic hypsec pulse

pypulseq/Sequence/read_seq.py, pypulseq/__init__.py
np.float is deprecated in numpy 1.20. Replacing it with the equivalent np.float64.
=> Replace np.float with np.float64

pypulseq/Sequence/ext_test_report.py, pypulseq/Sequence/sequence.py
Fixed several bugs in Sequence and test_report that result in incorrect test reports (e.g. wrong slew rates!) and incorrect k-space trajectory calculation.
Checked test reports for gre, tse, gre_radial, ute, and epi_se_rs to be identical with MATLAB.
Additionally made some minor changes that avoid some warnings (bad conditioning in polynomial fit and division by zero).
=> Bug fixes that produced incorrect test reports

pypulseq/Sequence/sequence.py
When we have RF pulses with non-zero start/end times, waveforms_and_times() function tries to add trailing/leading zeros as necessary to the beginning and end of the RF waveform. To avoid having duplicate times, leading zero is added at time `t[0]-eps,` trailing zero is added to the `t[-1]+eps`, where `eps` is supposedly "smallest floating increment". These are all inline with upstream MATLAB `Pulseq` implementation.
Trouble begins with the `eps`. `eps` is not actually the smallest increment. Floating point have variable increments depending on the number of significant digits. Quoting `numpy` documentation:
> 
> eps: float
> 
> The difference between 1.0 and the next smallest representable float larger than 1.0. For example, for 64-bit binary floats in the IEEE-754 standard, eps = …
=> Hacky fix for waveforms_and_times rf append floating point issue.

pypulseq/Sequence/sequence.py, pypulseq/make_trapezoid.py
Sequence.waveforms_and_times:
- Fixed missing implementation for recompressing trapezoids from arbitrary gradients. Now proceeds without recompressing and added a TODO to implement the MATLAB code.
- Fixed issue where rounding errors could create non-monotonically increasing times. Also moved the non-monotonicity check outside the loop.
make_trapezoid:
- Fixed bug that would give an 'requested area is too large' error when explicitly specifiying a triangular gradient with duration, rise_time, and area.
- Fixed check for area == 0, while an unspecified area would be None
=> Bug fixes in Sequence and make_trapezoid

pypulseq/Sequence/ext_test_report.py, pypulseq/Sequence/sequence.py, pypulseq/__init__.py, pypulseq/add_gradients.py, pypulseq/make_trapezoid.py, pypulseq/rotate.py
- Bypass code for `restoreAdditionalShapeSamples` did not include `grad.first` and `grad.last`
- `make_arbitrary_grad` was not available as `pp.make_arbitrary_grad`
- `add_gradients`' detection of arbitrary gradients was incorrect for Python's 0-based indexing
- `add_gradients` handling of non-unique times was broken
- `make_trapezoid` incorrectly checked and reported the minimum duration for gradients specifying area and duration (also fixed in local upstream MATLAB pulseq)
- `rotate` did not have a system parameter
- `rotate` used the incorrect channel for gradient on the second rotation axis
- Small change in `add_gradients` to accept a single gradient (i.e. for cases where a variable number of gradients are added), which also allowed a minor cleanup in `rotate`
=> Several bug fixes in `Sequence`, `add_gradients`, `make_trapezoid`, and `rotate`

pypulseq/Sequence/calc_pns.py, pypulseq/Sequence/sequence.py, pypulseq/seq_examples/scripts/pns_test.py, pypulseq/utils/safe_pns_prediction.py, pypulseq/utils/siemens/asc_to_hw.py, pypulseq/utils/siemens/readasc.py
This is a direct translation of the MATLAB Pulseq `calcPNS` function to python, renamed to `calculate_pns`. This includes a partial translation of the MATLAB safe_pns_prediction repository (https://github.com/filip-szczepankiewicz/safe_pns_prediction), put into utils/safe_pns_prediction.py. To test the functionality, this adds the pnsTest sequence "example" from MATLAB Pulseq.
A few, mostly stylistic, things may need some review:
- `readasc` and `asc_to_hw` are Siemens specific, might need to be put in a place for Siemens-specific code? (in Pulseq only `readasc` is separated)
- All functions from the SAFE code are in the same file, and maintain the MATLAB comments (as far as I'm concerned it really is not meant to be more than a direct translation). And what about license terms: …
=> Added PNS calculations

pypulseq/Sequence/block.py, pypulseq/Sequence/calc_pns.py, pypulseq/Sequence/ext_test_report.py, pypulseq/Sequence/read_seq.py, pypulseq/Sequence/sequence.py, pypulseq/Sequence/write_seq.py, pypulseq/__init__.py, pypulseq/add_gradients.py, pypulseq/block_to_events.py, pypulseq/calc_duration.py, pypulseq/calc_ramp.py, pypulseq/calc_rf_bandwidth.py, pypulseq/calc_rf_center.py, pypulseq/check_timing.py, pypulseq/compress_shape.py, pypulseq/event_lib.py, pypulseq/make_adiabatic_pulse.py, pypulseq/make_arbitrary_rf.py, pypulseq/make_block_pulse.py, pypulseq/make_extended_trapezoid.py, pypulseq/make_extended_trapezoid_area.py, pypulseq/make_gauss_pulse.py, pypulseq/make_sinc_pulse.py, pypulseq/make_trapezoid.py, pypulseq/points_to_waveform.py, pypulseq/rotate.py, pypulseq/split_gradient.py, pypulseq/split_gradient_at.py, pypulseq/utils/cumsum.py
- Replaced various calls to Numpy functions to native Python alternatives as this is much faster on scalar values and small lists (e.g. `max(a,b)` instead of `np.max([a,b])`).
- Replaced `np.cumsum` calls that used small, newly constructed lists with a native Python `cumsum`, specialized for up to 5 values (the maximum use-case found in pypulseq).
- Added caching of `get_block` to prevent expensive recalculations when blocks are repeatedly accessed.
- Replaced string-type dictionary keys with tuples in `event_lib` and `test_report`. This also fixes a bug where `event_lib.find_or_insert` would not find an existing event because a different key was used.
- Made `event_lib.find` use `next_free_ID` instead of recalculating this value every time.
- Optimized `compress_shape`, `add_gradients`, …
=> Performance improvements

pypulseq/Sequence/block.py, pypulseq/Sequence/ext_test_report.py, pypulseq/Sequence/read_seq.py, pypulseq/Sequence/sequence.py, pypulseq/Sequence/write_seq.py, pypulseq/seq_examples/scripts/write_gre.py
This implements `calculate_kspacePP` using scipy's `PPoly` object, which behaves very similar to the Matlab implementation. This is obviously much cleaner, and also much faster. A helper function `get_gradients` is also available to immediately get access to the waveforms in `PPoly` format.
I renamed the function to `calculate_kspace`, because this function was no longer functional, and not intended to be used anymore anyway. I added a deprecation warning for `calculate_kspacePP`, but this function could also just be removed altogether. This also resolves #107.
Furthermore, I split `waveforms_and_times` into three functions: `waveforms`, `adc_times`, and `rf_times`. This allows efficient access to for example only the excitation times (e.g. when only calculating TE/TR). …
=> Reworked piecewise polynomial implementation in Sequence to use scipy's PPoly

pypulseq/make_arbitrary_rf.py
Hi
I added a `no_signal_scaling` option to make_arbitrary_rf. This can be used for pulses where the flip-angle isn't linearly related to the pulse amplitude, e.g., adiabatic pulses.
I also added some missing documentation information.
=> Enh: New options in make_arbitrary_rf.py for adiabatic pulses

.github/requirements.yml, .github/workflows/push_pr.yml
Hi,
This PR enables running the included tests using the pytest module, utilising the Github CI / Actions facility. This was briefly discussed in Issue #119 . 
I've lifted this from my own python package https://github.com/wtclarke/nifti_mrs_tools/blob/master/.github/workflows/push_pr.yml. There's also an example in there for implementing a publishing pathway with the Github releases framework.
Note that the tests currently don't complete sucessfulyl as th `pypulseq/tests/matlab_seqs/` directory is missing from the repository.
=> Enh: Enable GitHub CI

setup.py
Hi folks, SigPy looks to have merged the NumPy fixes mentioned in #119  about 3 weeks ago - this PR just bumps the version in the setup.py file. I wasn't sure about patch version updates since versioning tracks Pulseq mainline, so the only change currenlty here is in the install_requires.
=> Bump sigpy version to 0.1.26

pypulseq/SAR/SAR_calc.py, pypulseq/make_trapezoid.py, pypulseq/tests/test_make_trapezoid.py
This should fix the issue described in #145. It also adds partial tests for the `make_trapezoid` function. Finally it removes a unused inport that was throwing warnings with tests in the `pypulseq/SAR/SAR_calc.py` module.
=> BF: make_trapezoid with amplitude + duration as inputs.

pypulseq/Sequence/sequence.py, pypulseq/make_gauss_pulse.py, pypulseq/tests/test_make_gauss_pulse.py, pypulseq/tests/test_sequence.py
Allow `show_blocks=True` to work in `seq.plot()` and allow all pulse uses for gaussian pulse.
=> BF: Minor bug fixes in sequence.py and make_gauss_pulse.py

.github/workflows/push_pr.yml, pypulseq/make_block_pulse.py, pypulseq/make_sigpy_pulse.py, pypulseq/tests/pytest.ini, pypulseq/tests/test_MPRAGE.py, pypulseq/tests/test_epi.py, pypulseq/tests/test_epi_label.py, pypulseq/tests/test_epi_se.py, pypulseq/tests/test_epi_se_rs.py, pypulseq/tests/test_gre.py, pypulseq/tests/test_gre_label.py, pypulseq/tests/test_gre_radial.py, pypulseq/tests/test_haste.py, pypulseq/tests/test_make_block_pulse.py, pypulseq/tests/test_sigpy.py, pypulseq/tests/test_tse.py, pypulseq/tests/test_ute.py
Addresses #149.
- Refines argument logic in `make_block_pulse`
- Refines documentation in `make_block_pulse`
- Adds tests for `make_block_pulse` (`test_make_block_pulse.py`)
- Adds markers for tests to exclude the original sequence comparisons whilst matlab generated sequences not committed.
=> BF: Refine argument options for make_block_pulse

pypulseq/Sequence/block.py
As title. There are two options here:
1. Only first commit: Give errors for all event types
2. Both commits: Give errors for RF/ADC events, but automatically add gradients together
Personally I'm in favour of option 2, because it seems like pretty natural behaviour, and it can come up in some instances: e.g. specifying a slab-selection refocusing gradient along with a phase-encoding gradient in 3D imaging. An argument against this behaviour is that it hides something the user should ideally be aware of, and you may end up with weird gradient shapes if the timing of gradients is not aligned.
=> Fixed `set_block` to give errors when multiple events of the same type are specified

pypulseq/Sequence/block.py, pypulseq/Sequence/calc_pns.py, pypulseq/Sequence/ext_test_report.py, pypulseq/Sequence/read_seq.py, pypulseq/Sequence/sequence.py, pypulseq/Sequence/write_seq.py, pypulseq/add_gradients.py, pypulseq/add_ramps.py, pypulseq/calc_ramp.py, pypulseq/event_lib.py, pypulseq/make_adc.py, pypulseq/make_adiabatic_pulse.py, pypulseq/make_arbitrary_grad.py, pypulseq/make_arbitrary_rf.py, pypulseq/make_block_pulse.py, pypulseq/make_digital_output_pulse.py, pypulseq/make_extended_trapezoid.py, pypulseq/make_gauss_pulse.py, pypulseq/make_sigpy_pulse.py, pypulseq/make_sinc_pulse.py, pypulseq/make_trapezoid.py, pypulseq/make_trigger.py, pypulseq/opts.py, pypulseq/rotate.py, pypulseq/split_gradient.py, pypulseq/split_gradient_at.py, pypulseq/traj_to_grad.py, pypulseq/utils/siemens/asc_to_hw.py
**Bug fixes:**
- `Sequence.adc_times` gave an error when no ADC events are in the sequence.
- `Sequence.read` now clears the block cache (e.g. if there already was a sequence loaded, `read` overwrites it, and should clear the block cache), and makes sure the block cache remains valid while filling in `grad.first` and `grad.last`.
- Fixed a small issue in `Sequence.read` where `grad.last` would not be filled in correctly (a larger issue with restoring these values remains, added a TODO note).
- Fixed `split_gradient`, which didn't work before.
- Fixed various pieces of code that assumed a linear ordering in the keys of `block_events`, which fixes https://github.com/pulseq/pulseq/issues/40. One small issue remains in `set_block`, where finding the previous block would be expensive, given …
=> Various bug fixes, features, and cleanups

pypulseq/Sequence/read_seq.py, pypulseq/event_lib.py
- Removed some references the to `lengths` field in `event_lib`. I removed this field in previous PRs because it was completely unused, but missed these uses.
- Fixed the handling of block durations and delays for 1.3.1 sequence files in `read_seq`.
Should fix #161
=> Fixed `read_seq` for reading v1.3.1 sequence files

pypulseq/Sequence/block.py, pypulseq/Sequence/sequence.py
This implements the `evalLabels` function from upstream pulseq: https://github.com/pulseq/pulseq/blob/125c772180f324967091dc28a0e5a6b20b96faa9/matlab/%2Bmr/%40Sequence/Sequence.m#L1056
Renamed to `evaluate_labels` to be consistent with the naming of other Sequence functions.
This function tracks labels (or label evolutions) through the sequence. Either returns the final values, or label evolutions (e.g. per block, per ADC, or whenever the label changes).
A small supporting change in `event_lib.get_block` was made to always set the `label` field in the returned block (None if no labels).
=> Feature: `evaluate_labels` function in `Sequence`

pypulseq/Sequence/block.py, pypulseq/Sequence/calc_pns.py, pypulseq/Sequence/read_seq.py, pypulseq/Sequence/sequence.py, pypulseq/make_sigpy_pulse.py, pypulseq/make_trapezoid.py, pypulseq/tests/test_sigpy.py, pypulseq/traj_to_grad.py, pypulseq/utils/siemens/readasc.py
- Fixed some rounding errors in `Sequence`
- Fixed possible warning for invalid escape sequence (e.g. `"(\s)+"` -> `r"(\s)+"`)
- Fixed reading back in string definitions that contain spaces (e.g. `seq.set_definition("a", "a a")`)
- Fixed an error in `calculate_kspace` when there are gradients specified on a gradient axis, but there are no ramps (i.e. all gradients are 0)
Edit, two more small bugs:
- Fixed an error with `next_free_block_ID` calculation when reading an empty sequence
- Fixed a bug in `traj_to_grad` and allow it to be used with a multidimensional k-space array
=> A few small bugfixes

pypulseq/add_gradients.py, pypulseq/event_lib.py, pypulseq/make_extended_trapezoid.py, pypulseq/opts.py
Fixed two small bugs:
- Missing `area` field in `make_extended_trapezoid`
- Extrapolation bug in `add_gradients` when adding arbitrary gradients
=> Bug fixes in `make_extended_trapezoid` and `add_gradients`

pypulseq/Sequence/calc_grad_spectrum.py, pypulseq/Sequence/sequence.py, pypulseq/utils/siemens/asc_to_hw.py
This PR adds the gradient spectrum calculation as available in MATLAB Pulseq: https://github.com/pulseq/pulseq/blob/master/matlab/demoUnsorted/gradSpectrum.m
The implementation provides a fair number of parameters to control how the calculation is actually done (as we're not entirely sure what is the best way to go about this). The defaults should be sufficient to avoid peaks in the spectrum at the acoustic resonances of your scanner (and avoid damaging the gradient coils).
Basic usage (will plot the spectrums and also return them):
```
seq.calculate_gradient_spectrum()
```
Or including plotting the acoustic resonance ranges from a Siemens .asc file:
```
from pypulseq.utils.siemens.readasc import readasc
from pypulseq.utils.siemens.asc_to_hw import asc_to_acoustic_resonances
asc = …
```
=> Added gradient spectrum calculations

pypulseq/make_extended_trapezoid_area.py, pypulseq/tests/test_make_extended_trapezoid_area.py
Improve timing/area calculation by ignoring raster_time at first and taking care of it in final calculation. This avoids issues by the discontinuities causing negative flat_times.
The issue accured for example when trying to use `make_extended_trapezoid_area` to calculate the rewinder gradients for spiral MRI sequences.
=> Fix make_extended_trapezoid area

pypulseq/Sequence/sequence.py, pypulseq/Sequence/write_seq.py
Due to the copy of `Sequence` object being made when `in_place=False`, assignments to the `self` in `write()` function is done to the copy, not the original. As a result, those values are not assigned after the call returns. AFAIK, only signature only these three lines are effected:
https://github.com/imr-framework/pypulseq/blob/10820cd22921eed477e0df7569949c9b8499f7e9/pypulseq/Sequence/write_seq.py#L261-L263
As a dummy workaround, I just passed `in_place=True` to the `remove_duplicates()`, but I think that is not what we want, as it will modify the `Sequence` object, is that true? In that case, my suggestion is to rename the copy, instead of assigning it to `self`, and still assigning signatures to `self` to keep old behavior. I can make that commit if you can confirm this is the desired …
=> `remove_duplicates()` without `in_place = True` causes `signature_value` to be not updated after `write`.

pypulseq/Sequence/sequence.py, pypulseq/supported_labels_rf_use.py
This PR adds "TRID" label (see pulseq/pulseq@682b9f1) to allow the GE interpreter to optimize the sequence by grouping consecutive blocks, removing the dead times between them. This is required to allow accurate execution of sequences designed for Siemens systems on GE systems.
=> feat: add TRID label (GE interpreter).

pypulseq/Sequence/sequence.py
As title, small bug in a change I made last week, causing `nan` values in gradient lookups in PNS and gradient spectrum calculations.
=> Changed `get_gradients` to actually use extrapolation in the piecewise polynomial

pypulseq/make_arbitrary_grad.py
The relevant change is the introduced area attribute:
`grad.area = (waveform * system.grad_raster_time).sum()`
The rest is minor refactoring and documentation.
=> Add area attribute for arbitrary gradients

pypulseq/__init__.py
As discussed in #129 with @FrankZijlstra and @btasdelen and many other issues/slack chats etc., the current value for the floating point precision `np.finfo(np.float64).eps` is only valid at the exact value of `1.0`. However, we ofen store larger values (we decided `1e6` is a reasonable upper limit for times, grad/rf amplitudes etc), leading to way worse precisions. 
I added a comment describing how we pick the new value of `eps = 1e-9` now and left the full calculation. Maybe one of both can be removed, but IMO you can never have to much documentation 😄 
In the future, we might want to define different eps values for times, gradients, rf pulses etc, but I think this value should actually cover everything without beeing to inaccurate.
=> Adjust eps value (floating point precision)

pypulseq/make_arbitrary_grad.py
The grad.first and grad.last attributes will probably be saved in the seq-file in the future. This PR allows to provide these values when creating the gradient, which is consistent with the [Matlab version](https://github.com/pulseq/pulseq/blob/master/matlab/%2Bmr/makeArbitraryGrad.m).
=> Add 'first' and 'last' arg to make_arbitrary_grad

pyproject.toml
With #195 we switched from `setup.py` to `pyproject.toml`, where we defined:
```toml
[tool.setuptools.packages.find]
where = ["pypulseq"]
```
This works fine when you install pypulseq from a local folder using `pip install .`, but not if you want to install it directly from GitHub using `pip install git+https://github.com/imr-framework/pypulseq`.
With the direct install from GitHub, no `pypulseq` package will be created, but only the modules in our pypulseq folder (like SAR, seq_examples, Sequence, ...) will be installed as packages. 
For me, removing the 2 lines above solves the problem, which makes sense IMO, because this is meant to tell setuptools where to look for our package and not which folder IS our package. Setuptools detects the src-layout, where the pypulseq folder would be in …
=> Fix direct install from GitHub repo

pypulseq/make_adiabatic_pulse.py, pypulseq/make_arbitrary_rf.py, pypulseq/make_block_pulse.py, pypulseq/make_gauss_pulse.py, pypulseq/make_sigpy_pulse.py, pypulseq/make_sinc_pulse.py, pypulseq/tests/test_make_adiabatic_pulse.py
This PR fixes an inconsistent behaviour of the "return_delay" argument for RF pulses. Currently, delays are returned only, if also "return_gz" is set to True, except for adiabatic pulses. However, sometimes it is useful to return a delay, even when no slice gradient is desired. The behaviour is now the same as in make_adiabatic_pulse.py
This PR also replaces the deprecated zero-filling at the end of an RF pulse for sigpy pulses by returning a delay instead.
=> Fix inconsistency in "return_delay" argument of RF pulses

pypulseq/make_trapezoid.py
Tries to address #213 
make_trapezoid() checks at the end if system.max_slew is exceeded. Similar to what is done with system.max_grad.
=> Assert that make_trapezoid() slew rate is smaller than max_slew

src/pypulseq/make_arbitrary_grad.py
Before this fix, it was not possible to set the `first` and/or `last` attribute to `0`, because `not 0` would always be true and thus the extrapolation was executed.
=> Fix None check in make_arbitrary_grad

src/pypulseq/make_block_pulse.py
This PR adds the same warning about the change of `rf.delay` to the method `make_block_pulse` as it is implemented in `make_sinc_pulse`. 
```
if rf.dead_time > rf.delay:
warn(
f'Specified RF delay {rf.delay*1e6:.2f} us is less than the dead time {rf.dead_time*1e6:.0f} us. Delay was increased to the dead time.',
stacklevel=2,
)
rf.delay = rf.dead_time
```
=> Add warning to make_block_pulse() if rf.delay is changed to rf.dead_time

.github/workflows/publish-to-pypi.yml, .github/workflows/push_pr.yml, examples/scripts/write_epi_se.py, pyproject.toml, tests/test_sequence.py, tests/test_sigpy.py
- set rf.dead_time of refocussing pulse in write_epi_se (was causing an error after merge of #236). Sorry, my fault!
- cleaned push_pr workflow:
- limit repository access to minimum
- added Python 3.12 to matrix
- included flag for sigpy tests in matrix (allows to run everything in parallel)
- removed unnecessary use of conda env in tests
- added dependency caching for speed up
- added concurrency to save resources and avoid unnecessary duplication
- added coverage report
- ensure test job fails if Failures or Errors occur
All in all, this hopefully simplifies the testing process, removes unnecessary complexity, and is generally better structured.
=> Fix tests, update workflows, support Python 3.12 tests

src/pypulseq/Sequence/read_seq.py
The extrapolation used to calculate grad.last was very buggy for arbitrary gradients leading to completely different results of seq.calculate_kspace() before/after writing the Sequence to a file and reading it in again.
Now the same extrapolation as in make_arbitrary_gradient is used. For my sequences, this fixed the problem
=> Fix grad.last calculation in read_seq function for arbitrary gradients

pyproject.toml
pytest-cov 6.1 changed the layout of the coverage output and is incompatilbe with the coverage comment action we use.
This PR pins the pytest-cov version to < 6.1
Thanks to @fzimmermann89 who fixed the same thing in [https://github.com/PTB-MR/mrpro/pull/758](https://github.com/PTB-MR/mrpro/pull/758)
=> Fix pytest coverage comment

src/pypulseq/make_extended_trapezoid_area.py, tests/test_make_extended_trapezoid_area.py
`make_extended_trapezoid_area` calls the `make_extended_trapezoid` function in the end to create the desired gradient. `make_extended_trapezoid` already supports the option to convert the resulting extended trapz gradient into an arbitrary gradient.
This PR simply introduces the option to set the `convert_to_arbitrary` flag in `make_extended_trapezoid_area` as well and parsing it to the `make_extended_trapezoid` function.
I kept the times and waveform arrays in the return values, although they are already available from the returned grad object. This became even clearer now due to the fact that I directly changed the return statement to `return grad, grad.tt, grad.waveform`
We might want to remove `grad.tt` and `grad.waveform` in the future, but I kept it in for backwards compatibility. …
=> Add convert_to_arbitrary option to make_extended_trapezoid_area function

src/pypulseq/make_arbitrary_grad.py, src/pypulseq/make_extended_trapezoid_area.py, src/pypulseq/make_trapezoid.py
Due to rounding issue checks for violating system specs in `make_trapezoid()` may fail, even though max values are not exceeded. For example the test below fails. Adding machine precision to the comparison solves the issue and fixes #267 
```
abs(amplitude2) > max_grad
125000.00000000001 > 125000
```
The error can be raised using this example script
```
from pypulseq import Opts
from pypulseq import make_trapezoid
system = Opts(
rf_dead_time=20e-6, 
rf_ringdown_time=30e-6,
grad_raster_time=1e-6,
rf_raster_time=1e-6,
block_duration_raster=1e-6,
adc_raster_time=1e-6,
max_grad=250e3 / 42.576e6 * 1e3,
grad_unit='mT/m',
max_slew=50,
slew_unit='T/m/s',
B0=50e-3,
gamma=42.576e6,
)
grad = make_trapezoid(
channel='x',
area=140.625,
system=system,
max_grad=125000.0,
)
print(grad.amplitude)  # …
```
=> Consider floating point accuracy for system specs checks

src/pypulseq/Sequence/sequence.py
This PR fixes #262 
Labels are plotted correctly for seq.plot(label='lin'). 
Can be tested with "write_epi_label.py" and "write_gre_label.py"
=> Fixes seq.plot() with labels issue #262

src/pypulseq/Sequence/ext_test_report.py
The test report prints gradient and slew rate values in **mT/m** and **T/m/s**, respectively. In the `ext_test_report` function the `convert` function is used to convert values from **Hz/m** and **Hz/m/s**, but gamma was not provided. Therefore, the default value for 1H was used, which lead to wrong values in the test report for other nuclei then 1H.
=> Fix test report for X-nuclei sequences

src/pypulseq/Sequence/sequence.py
`Sequence.calculate_kspace()` as well as `Sequence.get_gradients()` (should) support the `trajectory_delay` argument to be of type `Union[float, List[float], np.ndarray]` to be able to define individual delays for the 3 different gradient channels. However, in `Sequence.get_gradients()` there was an additional multiplication with `ng` (the number of grad channels), leading to too long lists in the case of input type list or wrong values in the case of input type np.array. 
The lines below handle the gradient_offset, where the implementation (without the multiplication with ng) is correct already. 
In the [matlab code](https://github.com/pulseq/pulseq/blob/c4ffd8250bef0a6b6f75b9e1ad275409d11b7727/matlab/%2Bmr/%40Sequence/Sequence.m#L2012) the factor is also NOT present.
=> Fix get_gradients function for channel specific gradient delays

src/pypulseq/make_arbitrary_grad.py
I realized there was a small bug in `make_arbitrary_grad`, where I forgot to assign `first` and `last` to the output `SimpleNamespace`. This PR fix this issue.
=> [towards v1.5.x] Fix missing first/last in make_arbitrary_grad
